# Generated by Django 2.1.7 on 2019-06-05 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_period', to='login.ItemCategory')),
                ('content_universitycareer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_universitycareer', to='login.ItemCategory')),
                ('type_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_event', to='login.ItemCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Content_info',
            fields=[
                ('content_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.CharField(max_length=45)),
                ('link_form', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('content_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Content_media',
            fields=[
                ('content_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('content_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Content')),
                ('item_category_item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ItemCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Info_site',
            fields=[
                ('info_site_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('orden', models.IntegerField()),
                ('item_category_item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ItemCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_requirements',
            fields=[
                ('pre_requirements_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('icon', models.CharField(max_length=45)),
                ('favicon', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_matter',
            fields=[
                ('subject_matter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_subject_matter', models.CharField(max_length=255)),
                ('universitycareer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ItemCategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('idSubMenu', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('orden', models.CharField(max_length=45)),
                ('menu_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='pre_requirements',
            name='subject_matter_id_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_matter_id_id', to='login.Subject_matter'),
        ),
        migrations.AddField(
            model_name='pre_requirements',
            name='subject_matter_requeriment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_matter_requeriment_id', to='login.Subject_matter'),
        ),
        migrations.AddField(
            model_name='info_site',
            name='site_site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Site'),
        ),
        migrations.AddField(
            model_name='info_site',
            name='type_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ItemCategory'),
        ),
    ]
