# Generated by Django 2.1.7 on 2019-06-13 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190607_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons_departaments',
            name='universitycareer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universitycareer', to='login.ItemCategory'),
        ),
        migrations.AlterField(
            model_name='persons_departaments',
            name='item_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_category_id', to='login.ItemCategory'),
        ),
    ]
